version: '3'

services:
  server:
    container_name: server_cdp
    restart: unless-stopped
    build: .
    environment:
      - DATABASE_URL=mongodb
      - WAIT_HOSTS=mongodb:27017
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo_cdp
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
