version: '3'

services:
  server:
    container_name: server_cdp
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mongo
      - WAIT_HOSTS=mongo:27017
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    container_name: mongo_cdp
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
